server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
